package com.shopping.rest.shopping_service.Model;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.annotation.Id;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Product class represents a product in the shopping system.
 * It contains product details such as name, category, price, discounts, special prices, and applicable coupons.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier for the product.
     * This is typically generated by MongoDB when the product is saved.
     */
    @Id
    private String productId;

    /**
     * Name of the product.
     */
    private String productName;

    /**
     * Category to which the product belongs, e.g., Electronics, Clothing, etc.
     */
    private String productCategory;

    /**
     * Regular price of the product before any discounts.
     */
    private BigDecimal price;

    /**
     * Discount applied to the product. This can be a fixed value or percentage.
     */
    private BigDecimal discount;

    /**
     * Special price of the product after applying the discount.
     * This field is calculated as price minus discount.
     */
    private BigDecimal specialPrice;

    /**
     * List of coupon IDs that can be applied to this product.
     * A product may have multiple applicable coupons.
     */
    private List<String> coupon;
}
